### PR TITLE
Generalize ghaction

### PR DESCRIPTION
**Pull request by wallento**

### CODE REVIEW

**Comment by olofk** [comment]
Looks good but can't merge yet. We use point to the subservient openlane_runner in other repos  so we need to detach them first

**Comment by wallento** [comment]
It's also draft at the moment. Does not work (yet). Do you have an overview of where you are using it?

**Comment by olofk** [comment]
This is probably a good start. https://github.com/klasnordmark/openlane-examples/issues/2

**Comment by wallento** [comment]
I restored the file. It is quite straight forward to add the logic to run the containerized runners from that script. But on the other hand we want to chase after its usages, right? Started with the first two PRs to fix it and will comment in the mentioned issue then.

**Comment by wallento** [comment]
Ready now

**Comment by olofk** [comment]
Cool! Let's go with this and we'll hunt the remaining users in time

**Pull request merged**
